//@generated by gentest/run.js from @file
import { it, expect } from "vitest";

import { Yoga } from "./init";

it("android_news_feed", function () {
  var config = Yoga.Config.create();

  try {
    var root = Yoga.Node.create(config);
    root.setAlignContent(Yoga.ALIGN_STRETCH);
    root.setWidth(1080);

    var root_child0 = Yoga.Node.create(config);
    root.insertChild(root_child0, 0);

    var root_child0_child0 = Yoga.Node.create(config);
    root_child0_child0.setAlignContent(Yoga.ALIGN_STRETCH);
    root_child0.insertChild(root_child0_child0, 0);

    var root_child0_child0_child0 = Yoga.Node.create(config);
    root_child0_child0_child0.setAlignContent(Yoga.ALIGN_STRETCH);
    root_child0_child0.insertChild(root_child0_child0_child0, 0);

    var root_child0_child0_child0_child0 = Yoga.Node.create(config);
    root_child0_child0_child0_child0.setFlexDirection(Yoga.FLEX_DIRECTION_ROW);
    root_child0_child0_child0_child0.setAlignContent(Yoga.ALIGN_STRETCH);
    root_child0_child0_child0_child0.setAlignItems(Yoga.ALIGN_FLEX_START);
    root_child0_child0_child0_child0.setMargin(Yoga.EDGE_START, 36);
    root_child0_child0_child0_child0.setMargin(Yoga.EDGE_TOP, 24);
    root_child0_child0_child0.insertChild(root_child0_child0_child0_child0, 0);

    var root_child0_child0_child0_child0_child0 = Yoga.Node.create(config);
    root_child0_child0_child0_child0_child0.setFlexDirection(Yoga.FLEX_DIRECTION_ROW);
    root_child0_child0_child0_child0_child0.setAlignContent(Yoga.ALIGN_STRETCH);
    root_child0_child0_child0_child0.insertChild(root_child0_child0_child0_child0_child0, 0);

    var root_child0_child0_child0_child0_child0_child0 = Yoga.Node.create(config);
    root_child0_child0_child0_child0_child0_child0.setAlignContent(Yoga.ALIGN_STRETCH);
    root_child0_child0_child0_child0_child0_child0.setWidth(120);
    root_child0_child0_child0_child0_child0_child0.setHeight(120);
    root_child0_child0_child0_child0_child0.insertChild(root_child0_child0_child0_child0_child0_child0, 0);

    var root_child0_child0_child0_child0_child1 = Yoga.Node.create(config);
    root_child0_child0_child0_child0_child1.setAlignContent(Yoga.ALIGN_STRETCH);
    root_child0_child0_child0_child0_child1.setFlexShrink(1);
    root_child0_child0_child0_child0_child1.setMargin(Yoga.EDGE_RIGHT, 36);
    root_child0_child0_child0_child0_child1.setPadding(Yoga.EDGE_LEFT, 36);
    root_child0_child0_child0_child0_child1.setPadding(Yoga.EDGE_TOP, 21);
    root_child0_child0_child0_child0_child1.setPadding(Yoga.EDGE_RIGHT, 36);
    root_child0_child0_child0_child0_child1.setPadding(Yoga.EDGE_BOTTOM, 18);
    root_child0_child0_child0_child0.insertChild(root_child0_child0_child0_child0_child1, 1);

    var root_child0_child0_child0_child0_child1_child0 = Yoga.Node.create(config);
    root_child0_child0_child0_child0_child1_child0.setFlexDirection(Yoga.FLEX_DIRECTION_ROW);
    root_child0_child0_child0_child0_child1_child0.setAlignContent(Yoga.ALIGN_STRETCH);
    root_child0_child0_child0_child0_child1_child0.setFlexShrink(1);
    root_child0_child0_child0_child0_child1.insertChild(root_child0_child0_child0_child0_child1_child0, 0);

    var root_child0_child0_child0_child0_child1_child1 = Yoga.Node.create(config);
    root_child0_child0_child0_child0_child1_child1.setAlignContent(Yoga.ALIGN_STRETCH);
    root_child0_child0_child0_child0_child1_child1.setFlexShrink(1);
    root_child0_child0_child0_child0_child1.insertChild(root_child0_child0_child0_child0_child1_child1, 1);

    var root_child0_child0_child1 = Yoga.Node.create(config);
    root_child0_child0_child1.setAlignContent(Yoga.ALIGN_STRETCH);
    root_child0_child0.insertChild(root_child0_child0_child1, 1);

    var root_child0_child0_child1_child0 = Yoga.Node.create(config);
    root_child0_child0_child1_child0.setFlexDirection(Yoga.FLEX_DIRECTION_ROW);
    root_child0_child0_child1_child0.setAlignContent(Yoga.ALIGN_STRETCH);
    root_child0_child0_child1_child0.setAlignItems(Yoga.ALIGN_FLEX_START);
    root_child0_child0_child1_child0.setMargin(Yoga.EDGE_START, 174);
    root_child0_child0_child1_child0.setMargin(Yoga.EDGE_TOP, 24);
    root_child0_child0_child1.insertChild(root_child0_child0_child1_child0, 0);

    var root_child0_child0_child1_child0_child0 = Yoga.Node.create(config);
    root_child0_child0_child1_child0_child0.setFlexDirection(Yoga.FLEX_DIRECTION_ROW);
    root_child0_child0_child1_child0_child0.setAlignContent(Yoga.ALIGN_STRETCH);
    root_child0_child0_child1_child0.insertChild(root_child0_child0_child1_child0_child0, 0);

    var root_child0_child0_child1_child0_child0_child0 = Yoga.Node.create(config);
    root_child0_child0_child1_child0_child0_child0.setAlignContent(Yoga.ALIGN_STRETCH);
    root_child0_child0_child1_child0_child0_child0.setWidth(72);
    root_child0_child0_child1_child0_child0_child0.setHeight(72);
    root_child0_child0_child1_child0_child0.insertChild(root_child0_child0_child1_child0_child0_child0, 0);

    var root_child0_child0_child1_child0_child1 = Yoga.Node.create(config);
    root_child0_child0_child1_child0_child1.setAlignContent(Yoga.ALIGN_STRETCH);
    root_child0_child0_child1_child0_child1.setFlexShrink(1);
    root_child0_child0_child1_child0_child1.setMargin(Yoga.EDGE_RIGHT, 36);
    root_child0_child0_child1_child0_child1.setPadding(Yoga.EDGE_LEFT, 36);
    root_child0_child0_child1_child0_child1.setPadding(Yoga.EDGE_TOP, 21);
    root_child0_child0_child1_child0_child1.setPadding(Yoga.EDGE_RIGHT, 36);
    root_child0_child0_child1_child0_child1.setPadding(Yoga.EDGE_BOTTOM, 18);
    root_child0_child0_child1_child0.insertChild(root_child0_child0_child1_child0_child1, 1);

    var root_child0_child0_child1_child0_child1_child0 = Yoga.Node.create(config);
    root_child0_child0_child1_child0_child1_child0.setFlexDirection(Yoga.FLEX_DIRECTION_ROW);
    root_child0_child0_child1_child0_child1_child0.setAlignContent(Yoga.ALIGN_STRETCH);
    root_child0_child0_child1_child0_child1_child0.setFlexShrink(1);
    root_child0_child0_child1_child0_child1.insertChild(root_child0_child0_child1_child0_child1_child0, 0);

    var root_child0_child0_child1_child0_child1_child1 = Yoga.Node.create(config);
    root_child0_child0_child1_child0_child1_child1.setAlignContent(Yoga.ALIGN_STRETCH);
    root_child0_child0_child1_child0_child1_child1.setFlexShrink(1);
    root_child0_child0_child1_child0_child1.insertChild(root_child0_child0_child1_child0_child1_child1, 1);
    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_LTR);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "1080 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(1080);;
    expect(
      root.getComputedHeight(),
      "240 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(240);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "1080 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(1080);;
    expect(
      root_child0.getComputedHeight(),
      "240 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(240);;

    expect(
      root_child0_child0.getComputedLeft(),
      "0 === root_child0_child0.getComputedLeft() (" + root_child0_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0.getComputedTop(),
      "0 === root_child0_child0.getComputedTop() (" + root_child0_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0.getComputedWidth(),
      "1080 === root_child0_child0.getComputedWidth() (" + root_child0_child0.getComputedWidth() + ")"
    ).toBe(1080);;
    expect(
      root_child0_child0.getComputedHeight(),
      "240 === root_child0_child0.getComputedHeight() (" + root_child0_child0.getComputedHeight() + ")"
    ).toBe(240);;

    expect(
      root_child0_child0_child0.getComputedLeft(),
      "0 === root_child0_child0_child0.getComputedLeft() (" + root_child0_child0_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child0.getComputedTop(),
      "0 === root_child0_child0_child0.getComputedTop() (" + root_child0_child0_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child0.getComputedWidth(),
      "1080 === root_child0_child0_child0.getComputedWidth() (" + root_child0_child0_child0.getComputedWidth() + ")"
    ).toBe(1080);;
    expect(
      root_child0_child0_child0.getComputedHeight(),
      "144 === root_child0_child0_child0.getComputedHeight() (" + root_child0_child0_child0.getComputedHeight() + ")"
    ).toBe(144);;

    expect(
      root_child0_child0_child0_child0.getComputedLeft(),
      "36 === root_child0_child0_child0_child0.getComputedLeft() (" + root_child0_child0_child0_child0.getComputedLeft() + ")"
    ).toBe(36);;
    expect(
      root_child0_child0_child0_child0.getComputedTop(),
      "24 === root_child0_child0_child0_child0.getComputedTop() (" + root_child0_child0_child0_child0.getComputedTop() + ")"
    ).toBe(24);;
    expect(
      root_child0_child0_child0_child0.getComputedWidth(),
      "1044 === root_child0_child0_child0_child0.getComputedWidth() (" + root_child0_child0_child0_child0.getComputedWidth() + ")"
    ).toBe(1044);;
    expect(
      root_child0_child0_child0_child0.getComputedHeight(),
      "120 === root_child0_child0_child0_child0.getComputedHeight() (" + root_child0_child0_child0_child0.getComputedHeight() + ")"
    ).toBe(120);;

    expect(
      root_child0_child0_child0_child0_child0.getComputedLeft(),
      "0 === root_child0_child0_child0_child0_child0.getComputedLeft() (" + root_child0_child0_child0_child0_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child0_child0_child0.getComputedTop(),
      "0 === root_child0_child0_child0_child0_child0.getComputedTop() (" + root_child0_child0_child0_child0_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child0_child0_child0.getComputedWidth(),
      "120 === root_child0_child0_child0_child0_child0.getComputedWidth() (" + root_child0_child0_child0_child0_child0.getComputedWidth() + ")"
    ).toBe(120);;
    expect(
      root_child0_child0_child0_child0_child0.getComputedHeight(),
      "120 === root_child0_child0_child0_child0_child0.getComputedHeight() (" + root_child0_child0_child0_child0_child0.getComputedHeight() + ")"
    ).toBe(120);;

    expect(
      root_child0_child0_child0_child0_child0_child0.getComputedLeft(),
      "0 === root_child0_child0_child0_child0_child0_child0.getComputedLeft() (" + root_child0_child0_child0_child0_child0_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child0_child0_child0_child0.getComputedTop(),
      "0 === root_child0_child0_child0_child0_child0_child0.getComputedTop() (" + root_child0_child0_child0_child0_child0_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child0_child0_child0_child0.getComputedWidth(),
      "120 === root_child0_child0_child0_child0_child0_child0.getComputedWidth() (" + root_child0_child0_child0_child0_child0_child0.getComputedWidth() + ")"
    ).toBe(120);;
    expect(
      root_child0_child0_child0_child0_child0_child0.getComputedHeight(),
      "120 === root_child0_child0_child0_child0_child0_child0.getComputedHeight() (" + root_child0_child0_child0_child0_child0_child0.getComputedHeight() + ")"
    ).toBe(120);;

    expect(
      root_child0_child0_child0_child0_child1.getComputedLeft(),
      "120 === root_child0_child0_child0_child0_child1.getComputedLeft() (" + root_child0_child0_child0_child0_child1.getComputedLeft() + ")"
    ).toBe(120);;
    expect(
      root_child0_child0_child0_child0_child1.getComputedTop(),
      "0 === root_child0_child0_child0_child0_child1.getComputedTop() (" + root_child0_child0_child0_child0_child1.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child0_child0_child1.getComputedWidth(),
      "72 === root_child0_child0_child0_child0_child1.getComputedWidth() (" + root_child0_child0_child0_child0_child1.getComputedWidth() + ")"
    ).toBe(72);;
    expect(
      root_child0_child0_child0_child0_child1.getComputedHeight(),
      "39 === root_child0_child0_child0_child0_child1.getComputedHeight() (" + root_child0_child0_child0_child0_child1.getComputedHeight() + ")"
    ).toBe(39);;

    expect(
      root_child0_child0_child0_child0_child1_child0.getComputedLeft(),
      "36 === root_child0_child0_child0_child0_child1_child0.getComputedLeft() (" + root_child0_child0_child0_child0_child1_child0.getComputedLeft() + ")"
    ).toBe(36);;
    expect(
      root_child0_child0_child0_child0_child1_child0.getComputedTop(),
      "21 === root_child0_child0_child0_child0_child1_child0.getComputedTop() (" + root_child0_child0_child0_child0_child1_child0.getComputedTop() + ")"
    ).toBe(21);;
    expect(
      root_child0_child0_child0_child0_child1_child0.getComputedWidth(),
      "0 === root_child0_child0_child0_child0_child1_child0.getComputedWidth() (" + root_child0_child0_child0_child0_child1_child0.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child0_child0_child1_child0.getComputedHeight(),
      "0 === root_child0_child0_child0_child0_child1_child0.getComputedHeight() (" + root_child0_child0_child0_child0_child1_child0.getComputedHeight() + ")"
    ).toBe(0);;

    expect(
      root_child0_child0_child0_child0_child1_child1.getComputedLeft(),
      "36 === root_child0_child0_child0_child0_child1_child1.getComputedLeft() (" + root_child0_child0_child0_child0_child1_child1.getComputedLeft() + ")"
    ).toBe(36);;
    expect(
      root_child0_child0_child0_child0_child1_child1.getComputedTop(),
      "21 === root_child0_child0_child0_child0_child1_child1.getComputedTop() (" + root_child0_child0_child0_child0_child1_child1.getComputedTop() + ")"
    ).toBe(21);;
    expect(
      root_child0_child0_child0_child0_child1_child1.getComputedWidth(),
      "0 === root_child0_child0_child0_child0_child1_child1.getComputedWidth() (" + root_child0_child0_child0_child0_child1_child1.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child0_child0_child1_child1.getComputedHeight(),
      "0 === root_child0_child0_child0_child0_child1_child1.getComputedHeight() (" + root_child0_child0_child0_child0_child1_child1.getComputedHeight() + ")"
    ).toBe(0);;

    expect(
      root_child0_child0_child1.getComputedLeft(),
      "0 === root_child0_child0_child1.getComputedLeft() (" + root_child0_child0_child1.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child1.getComputedTop(),
      "144 === root_child0_child0_child1.getComputedTop() (" + root_child0_child0_child1.getComputedTop() + ")"
    ).toBe(144);;
    expect(
      root_child0_child0_child1.getComputedWidth(),
      "1080 === root_child0_child0_child1.getComputedWidth() (" + root_child0_child0_child1.getComputedWidth() + ")"
    ).toBe(1080);;
    expect(
      root_child0_child0_child1.getComputedHeight(),
      "96 === root_child0_child0_child1.getComputedHeight() (" + root_child0_child0_child1.getComputedHeight() + ")"
    ).toBe(96);;

    expect(
      root_child0_child0_child1_child0.getComputedLeft(),
      "174 === root_child0_child0_child1_child0.getComputedLeft() (" + root_child0_child0_child1_child0.getComputedLeft() + ")"
    ).toBe(174);;
    expect(
      root_child0_child0_child1_child0.getComputedTop(),
      "24 === root_child0_child0_child1_child0.getComputedTop() (" + root_child0_child0_child1_child0.getComputedTop() + ")"
    ).toBe(24);;
    expect(
      root_child0_child0_child1_child0.getComputedWidth(),
      "906 === root_child0_child0_child1_child0.getComputedWidth() (" + root_child0_child0_child1_child0.getComputedWidth() + ")"
    ).toBe(906);;
    expect(
      root_child0_child0_child1_child0.getComputedHeight(),
      "72 === root_child0_child0_child1_child0.getComputedHeight() (" + root_child0_child0_child1_child0.getComputedHeight() + ")"
    ).toBe(72);;

    expect(
      root_child0_child0_child1_child0_child0.getComputedLeft(),
      "0 === root_child0_child0_child1_child0_child0.getComputedLeft() (" + root_child0_child0_child1_child0_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child1_child0_child0.getComputedTop(),
      "0 === root_child0_child0_child1_child0_child0.getComputedTop() (" + root_child0_child0_child1_child0_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child1_child0_child0.getComputedWidth(),
      "72 === root_child0_child0_child1_child0_child0.getComputedWidth() (" + root_child0_child0_child1_child0_child0.getComputedWidth() + ")"
    ).toBe(72);;
    expect(
      root_child0_child0_child1_child0_child0.getComputedHeight(),
      "72 === root_child0_child0_child1_child0_child0.getComputedHeight() (" + root_child0_child0_child1_child0_child0.getComputedHeight() + ")"
    ).toBe(72);;

    expect(
      root_child0_child0_child1_child0_child0_child0.getComputedLeft(),
      "0 === root_child0_child0_child1_child0_child0_child0.getComputedLeft() (" + root_child0_child0_child1_child0_child0_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child1_child0_child0_child0.getComputedTop(),
      "0 === root_child0_child0_child1_child0_child0_child0.getComputedTop() (" + root_child0_child0_child1_child0_child0_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child1_child0_child0_child0.getComputedWidth(),
      "72 === root_child0_child0_child1_child0_child0_child0.getComputedWidth() (" + root_child0_child0_child1_child0_child0_child0.getComputedWidth() + ")"
    ).toBe(72);;
    expect(
      root_child0_child0_child1_child0_child0_child0.getComputedHeight(),
      "72 === root_child0_child0_child1_child0_child0_child0.getComputedHeight() (" + root_child0_child0_child1_child0_child0_child0.getComputedHeight() + ")"
    ).toBe(72);;

    expect(
      root_child0_child0_child1_child0_child1.getComputedLeft(),
      "72 === root_child0_child0_child1_child0_child1.getComputedLeft() (" + root_child0_child0_child1_child0_child1.getComputedLeft() + ")"
    ).toBe(72);;
    expect(
      root_child0_child0_child1_child0_child1.getComputedTop(),
      "0 === root_child0_child0_child1_child0_child1.getComputedTop() (" + root_child0_child0_child1_child0_child1.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child1_child0_child1.getComputedWidth(),
      "72 === root_child0_child0_child1_child0_child1.getComputedWidth() (" + root_child0_child0_child1_child0_child1.getComputedWidth() + ")"
    ).toBe(72);;
    expect(
      root_child0_child0_child1_child0_child1.getComputedHeight(),
      "39 === root_child0_child0_child1_child0_child1.getComputedHeight() (" + root_child0_child0_child1_child0_child1.getComputedHeight() + ")"
    ).toBe(39);;

    expect(
      root_child0_child0_child1_child0_child1_child0.getComputedLeft(),
      "36 === root_child0_child0_child1_child0_child1_child0.getComputedLeft() (" + root_child0_child0_child1_child0_child1_child0.getComputedLeft() + ")"
    ).toBe(36);;
    expect(
      root_child0_child0_child1_child0_child1_child0.getComputedTop(),
      "21 === root_child0_child0_child1_child0_child1_child0.getComputedTop() (" + root_child0_child0_child1_child0_child1_child0.getComputedTop() + ")"
    ).toBe(21);;
    expect(
      root_child0_child0_child1_child0_child1_child0.getComputedWidth(),
      "0 === root_child0_child0_child1_child0_child1_child0.getComputedWidth() (" + root_child0_child0_child1_child0_child1_child0.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child1_child0_child1_child0.getComputedHeight(),
      "0 === root_child0_child0_child1_child0_child1_child0.getComputedHeight() (" + root_child0_child0_child1_child0_child1_child0.getComputedHeight() + ")"
    ).toBe(0);;

    expect(
      root_child0_child0_child1_child0_child1_child1.getComputedLeft(),
      "36 === root_child0_child0_child1_child0_child1_child1.getComputedLeft() (" + root_child0_child0_child1_child0_child1_child1.getComputedLeft() + ")"
    ).toBe(36);;
    expect(
      root_child0_child0_child1_child0_child1_child1.getComputedTop(),
      "21 === root_child0_child0_child1_child0_child1_child1.getComputedTop() (" + root_child0_child0_child1_child0_child1_child1.getComputedTop() + ")"
    ).toBe(21);;
    expect(
      root_child0_child0_child1_child0_child1_child1.getComputedWidth(),
      "0 === root_child0_child0_child1_child0_child1_child1.getComputedWidth() (" + root_child0_child0_child1_child0_child1_child1.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child1_child0_child1_child1.getComputedHeight(),
      "0 === root_child0_child0_child1_child0_child1_child1.getComputedHeight() (" + root_child0_child0_child1_child0_child1_child1.getComputedHeight() + ")"
    ).toBe(0);;

    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_RTL);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "1080 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(1080);;
    expect(
      root.getComputedHeight(),
      "240 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(240);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "1080 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(1080);;
    expect(
      root_child0.getComputedHeight(),
      "240 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(240);;

    expect(
      root_child0_child0.getComputedLeft(),
      "0 === root_child0_child0.getComputedLeft() (" + root_child0_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0.getComputedTop(),
      "0 === root_child0_child0.getComputedTop() (" + root_child0_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0.getComputedWidth(),
      "1080 === root_child0_child0.getComputedWidth() (" + root_child0_child0.getComputedWidth() + ")"
    ).toBe(1080);;
    expect(
      root_child0_child0.getComputedHeight(),
      "240 === root_child0_child0.getComputedHeight() (" + root_child0_child0.getComputedHeight() + ")"
    ).toBe(240);;

    expect(
      root_child0_child0_child0.getComputedLeft(),
      "0 === root_child0_child0_child0.getComputedLeft() (" + root_child0_child0_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child0.getComputedTop(),
      "0 === root_child0_child0_child0.getComputedTop() (" + root_child0_child0_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child0.getComputedWidth(),
      "1080 === root_child0_child0_child0.getComputedWidth() (" + root_child0_child0_child0.getComputedWidth() + ")"
    ).toBe(1080);;
    expect(
      root_child0_child0_child0.getComputedHeight(),
      "144 === root_child0_child0_child0.getComputedHeight() (" + root_child0_child0_child0.getComputedHeight() + ")"
    ).toBe(144);;

    expect(
      root_child0_child0_child0_child0.getComputedLeft(),
      "0 === root_child0_child0_child0_child0.getComputedLeft() (" + root_child0_child0_child0_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child0_child0.getComputedTop(),
      "24 === root_child0_child0_child0_child0.getComputedTop() (" + root_child0_child0_child0_child0.getComputedTop() + ")"
    ).toBe(24);;
    expect(
      root_child0_child0_child0_child0.getComputedWidth(),
      "1044 === root_child0_child0_child0_child0.getComputedWidth() (" + root_child0_child0_child0_child0.getComputedWidth() + ")"
    ).toBe(1044);;
    expect(
      root_child0_child0_child0_child0.getComputedHeight(),
      "120 === root_child0_child0_child0_child0.getComputedHeight() (" + root_child0_child0_child0_child0.getComputedHeight() + ")"
    ).toBe(120);;

    expect(
      root_child0_child0_child0_child0_child0.getComputedLeft(),
      "924 === root_child0_child0_child0_child0_child0.getComputedLeft() (" + root_child0_child0_child0_child0_child0.getComputedLeft() + ")"
    ).toBe(924);;
    expect(
      root_child0_child0_child0_child0_child0.getComputedTop(),
      "0 === root_child0_child0_child0_child0_child0.getComputedTop() (" + root_child0_child0_child0_child0_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child0_child0_child0.getComputedWidth(),
      "120 === root_child0_child0_child0_child0_child0.getComputedWidth() (" + root_child0_child0_child0_child0_child0.getComputedWidth() + ")"
    ).toBe(120);;
    expect(
      root_child0_child0_child0_child0_child0.getComputedHeight(),
      "120 === root_child0_child0_child0_child0_child0.getComputedHeight() (" + root_child0_child0_child0_child0_child0.getComputedHeight() + ")"
    ).toBe(120);;

    expect(
      root_child0_child0_child0_child0_child0_child0.getComputedLeft(),
      "0 === root_child0_child0_child0_child0_child0_child0.getComputedLeft() (" + root_child0_child0_child0_child0_child0_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child0_child0_child0_child0.getComputedTop(),
      "0 === root_child0_child0_child0_child0_child0_child0.getComputedTop() (" + root_child0_child0_child0_child0_child0_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child0_child0_child0_child0.getComputedWidth(),
      "120 === root_child0_child0_child0_child0_child0_child0.getComputedWidth() (" + root_child0_child0_child0_child0_child0_child0.getComputedWidth() + ")"
    ).toBe(120);;
    expect(
      root_child0_child0_child0_child0_child0_child0.getComputedHeight(),
      "120 === root_child0_child0_child0_child0_child0_child0.getComputedHeight() (" + root_child0_child0_child0_child0_child0_child0.getComputedHeight() + ")"
    ).toBe(120);;

    expect(
      root_child0_child0_child0_child0_child1.getComputedLeft(),
      "816 === root_child0_child0_child0_child0_child1.getComputedLeft() (" + root_child0_child0_child0_child0_child1.getComputedLeft() + ")"
    ).toBe(816);;
    expect(
      root_child0_child0_child0_child0_child1.getComputedTop(),
      "0 === root_child0_child0_child0_child0_child1.getComputedTop() (" + root_child0_child0_child0_child0_child1.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child0_child0_child1.getComputedWidth(),
      "72 === root_child0_child0_child0_child0_child1.getComputedWidth() (" + root_child0_child0_child0_child0_child1.getComputedWidth() + ")"
    ).toBe(72);;
    expect(
      root_child0_child0_child0_child0_child1.getComputedHeight(),
      "39 === root_child0_child0_child0_child0_child1.getComputedHeight() (" + root_child0_child0_child0_child0_child1.getComputedHeight() + ")"
    ).toBe(39);;

    expect(
      root_child0_child0_child0_child0_child1_child0.getComputedLeft(),
      "36 === root_child0_child0_child0_child0_child1_child0.getComputedLeft() (" + root_child0_child0_child0_child0_child1_child0.getComputedLeft() + ")"
    ).toBe(36);;
    expect(
      root_child0_child0_child0_child0_child1_child0.getComputedTop(),
      "21 === root_child0_child0_child0_child0_child1_child0.getComputedTop() (" + root_child0_child0_child0_child0_child1_child0.getComputedTop() + ")"
    ).toBe(21);;
    expect(
      root_child0_child0_child0_child0_child1_child0.getComputedWidth(),
      "0 === root_child0_child0_child0_child0_child1_child0.getComputedWidth() (" + root_child0_child0_child0_child0_child1_child0.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child0_child0_child1_child0.getComputedHeight(),
      "0 === root_child0_child0_child0_child0_child1_child0.getComputedHeight() (" + root_child0_child0_child0_child0_child1_child0.getComputedHeight() + ")"
    ).toBe(0);;

    expect(
      root_child0_child0_child0_child0_child1_child1.getComputedLeft(),
      "36 === root_child0_child0_child0_child0_child1_child1.getComputedLeft() (" + root_child0_child0_child0_child0_child1_child1.getComputedLeft() + ")"
    ).toBe(36);;
    expect(
      root_child0_child0_child0_child0_child1_child1.getComputedTop(),
      "21 === root_child0_child0_child0_child0_child1_child1.getComputedTop() (" + root_child0_child0_child0_child0_child1_child1.getComputedTop() + ")"
    ).toBe(21);;
    expect(
      root_child0_child0_child0_child0_child1_child1.getComputedWidth(),
      "0 === root_child0_child0_child0_child0_child1_child1.getComputedWidth() (" + root_child0_child0_child0_child0_child1_child1.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child0_child0_child1_child1.getComputedHeight(),
      "0 === root_child0_child0_child0_child0_child1_child1.getComputedHeight() (" + root_child0_child0_child0_child0_child1_child1.getComputedHeight() + ")"
    ).toBe(0);;

    expect(
      root_child0_child0_child1.getComputedLeft(),
      "0 === root_child0_child0_child1.getComputedLeft() (" + root_child0_child0_child1.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child1.getComputedTop(),
      "144 === root_child0_child0_child1.getComputedTop() (" + root_child0_child0_child1.getComputedTop() + ")"
    ).toBe(144);;
    expect(
      root_child0_child0_child1.getComputedWidth(),
      "1080 === root_child0_child0_child1.getComputedWidth() (" + root_child0_child0_child1.getComputedWidth() + ")"
    ).toBe(1080);;
    expect(
      root_child0_child0_child1.getComputedHeight(),
      "96 === root_child0_child0_child1.getComputedHeight() (" + root_child0_child0_child1.getComputedHeight() + ")"
    ).toBe(96);;

    expect(
      root_child0_child0_child1_child0.getComputedLeft(),
      "0 === root_child0_child0_child1_child0.getComputedLeft() (" + root_child0_child0_child1_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child1_child0.getComputedTop(),
      "24 === root_child0_child0_child1_child0.getComputedTop() (" + root_child0_child0_child1_child0.getComputedTop() + ")"
    ).toBe(24);;
    expect(
      root_child0_child0_child1_child0.getComputedWidth(),
      "906 === root_child0_child0_child1_child0.getComputedWidth() (" + root_child0_child0_child1_child0.getComputedWidth() + ")"
    ).toBe(906);;
    expect(
      root_child0_child0_child1_child0.getComputedHeight(),
      "72 === root_child0_child0_child1_child0.getComputedHeight() (" + root_child0_child0_child1_child0.getComputedHeight() + ")"
    ).toBe(72);;

    expect(
      root_child0_child0_child1_child0_child0.getComputedLeft(),
      "834 === root_child0_child0_child1_child0_child0.getComputedLeft() (" + root_child0_child0_child1_child0_child0.getComputedLeft() + ")"
    ).toBe(834);;
    expect(
      root_child0_child0_child1_child0_child0.getComputedTop(),
      "0 === root_child0_child0_child1_child0_child0.getComputedTop() (" + root_child0_child0_child1_child0_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child1_child0_child0.getComputedWidth(),
      "72 === root_child0_child0_child1_child0_child0.getComputedWidth() (" + root_child0_child0_child1_child0_child0.getComputedWidth() + ")"
    ).toBe(72);;
    expect(
      root_child0_child0_child1_child0_child0.getComputedHeight(),
      "72 === root_child0_child0_child1_child0_child0.getComputedHeight() (" + root_child0_child0_child1_child0_child0.getComputedHeight() + ")"
    ).toBe(72);;

    expect(
      root_child0_child0_child1_child0_child0_child0.getComputedLeft(),
      "0 === root_child0_child0_child1_child0_child0_child0.getComputedLeft() (" + root_child0_child0_child1_child0_child0_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child1_child0_child0_child0.getComputedTop(),
      "0 === root_child0_child0_child1_child0_child0_child0.getComputedTop() (" + root_child0_child0_child1_child0_child0_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child1_child0_child0_child0.getComputedWidth(),
      "72 === root_child0_child0_child1_child0_child0_child0.getComputedWidth() (" + root_child0_child0_child1_child0_child0_child0.getComputedWidth() + ")"
    ).toBe(72);;
    expect(
      root_child0_child0_child1_child0_child0_child0.getComputedHeight(),
      "72 === root_child0_child0_child1_child0_child0_child0.getComputedHeight() (" + root_child0_child0_child1_child0_child0_child0.getComputedHeight() + ")"
    ).toBe(72);;

    expect(
      root_child0_child0_child1_child0_child1.getComputedLeft(),
      "726 === root_child0_child0_child1_child0_child1.getComputedLeft() (" + root_child0_child0_child1_child0_child1.getComputedLeft() + ")"
    ).toBe(726);;
    expect(
      root_child0_child0_child1_child0_child1.getComputedTop(),
      "0 === root_child0_child0_child1_child0_child1.getComputedTop() (" + root_child0_child0_child1_child0_child1.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child1_child0_child1.getComputedWidth(),
      "72 === root_child0_child0_child1_child0_child1.getComputedWidth() (" + root_child0_child0_child1_child0_child1.getComputedWidth() + ")"
    ).toBe(72);;
    expect(
      root_child0_child0_child1_child0_child1.getComputedHeight(),
      "39 === root_child0_child0_child1_child0_child1.getComputedHeight() (" + root_child0_child0_child1_child0_child1.getComputedHeight() + ")"
    ).toBe(39);;

    expect(
      root_child0_child0_child1_child0_child1_child0.getComputedLeft(),
      "36 === root_child0_child0_child1_child0_child1_child0.getComputedLeft() (" + root_child0_child0_child1_child0_child1_child0.getComputedLeft() + ")"
    ).toBe(36);;
    expect(
      root_child0_child0_child1_child0_child1_child0.getComputedTop(),
      "21 === root_child0_child0_child1_child0_child1_child0.getComputedTop() (" + root_child0_child0_child1_child0_child1_child0.getComputedTop() + ")"
    ).toBe(21);;
    expect(
      root_child0_child0_child1_child0_child1_child0.getComputedWidth(),
      "0 === root_child0_child0_child1_child0_child1_child0.getComputedWidth() (" + root_child0_child0_child1_child0_child1_child0.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child1_child0_child1_child0.getComputedHeight(),
      "0 === root_child0_child0_child1_child0_child1_child0.getComputedHeight() (" + root_child0_child0_child1_child0_child1_child0.getComputedHeight() + ")"
    ).toBe(0);;

    expect(
      root_child0_child0_child1_child0_child1_child1.getComputedLeft(),
      "36 === root_child0_child0_child1_child0_child1_child1.getComputedLeft() (" + root_child0_child0_child1_child0_child1_child1.getComputedLeft() + ")"
    ).toBe(36);;
    expect(
      root_child0_child0_child1_child0_child1_child1.getComputedTop(),
      "21 === root_child0_child0_child1_child0_child1_child1.getComputedTop() (" + root_child0_child0_child1_child0_child1_child1.getComputedTop() + ")"
    ).toBe(21);;
    expect(
      root_child0_child0_child1_child0_child1_child1.getComputedWidth(),
      "0 === root_child0_child0_child1_child0_child1_child1.getComputedWidth() (" + root_child0_child0_child1_child0_child1_child1.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0_child1_child0_child1_child1.getComputedHeight(),
      "0 === root_child0_child0_child1_child0_child1_child1.getComputedHeight() (" + root_child0_child0_child1_child0_child1_child1.getComputedHeight() + ")"
    ).toBe(0);;
  } finally {
    if (typeof root !== "undefined") {
      root.freeRecursive();
    }

    config.free();
  }
});
