//@generated by gentest/run.js from @file
import { it, expect } from "vitest";

import { Yoga } from "./init";

it("padding_start", function () {
  var root = Yoga.Node.create();
  root.setWidth(100);
  root.setHeight(100);
  root.setPadding(Yoga.EDGE_START, `10%`);

  root.calculateLayout(100, 100, Yoga.DIRECTION_LTR);

  expect(
    root.getComputedPadding(Yoga.EDGE_LEFT),
    "10 === root.getComputedPadding(Yoga.EDGE_LEFT)"
  ).toBe(10);;
  expect(
    root.getComputedPadding(Yoga.EDGE_RIGHT),
    "0 === root.getComputedPadding(Yoga.EDGE_RIGHT)"
  ).toBe(0);;

  root.calculateLayout(100, 100, Yoga.DIRECTION_RTL);

  expect(
    root.getComputedPadding(Yoga.EDGE_LEFT),
    "0 === root.getComputedPadding(Yoga.EDGE_LEFT)"
  ).toBe(0);;
  expect(
    root.getComputedPadding(Yoga.EDGE_RIGHT),
    "10 === root.getComputedPadding(Yoga.EDGE_RIGHT)"
  ).toBe(10);;

  if (typeof root !== "undefined")
    root.freeRecursive();

  (typeof gc !== "undefined") && gc();
  // TODO Add event support in js and check instace allocation and de allocation using that
});
