//@generated by gentest/run.js from @file
import { it, expect } from "vitest";

import { Yoga } from "./init";
import { getMeasureCounter } from "./tools";

it("dont_measure_single_grow_shrink_child", function () {
  var root = Yoga.Node.create();
  root.setWidth(100);
  root.setHeight(100);

  var measureCounter = getMeasureCounter(Yoga, null, 100, 100);

  var root_child0 = Yoga.Node.create();
  root_child0.setMeasureFunc(measureCounter.inc);
  root_child0.setFlexGrow(1);
  root_child0.setFlexShrink(1);
  root.insertChild(root_child0, 0);
  root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_LTR);

  expect(
    measureCounter.get(),
    "0 === measureCounter.get() (" + measureCounter.get() + ")"
  ).toBe(0);;

  if (typeof root !== "undefined")
    root.freeRecursive();

  (typeof gc !== "undefined") && gc();
  // TODO Add event support in js and check instace allocation and de allocation using that
});
