//@generated by gentest/run.js from @file
import { it, expect } from "vitest";

import { Yoga } from "./init";

it("max_width", function () {
  var config = Yoga.Config.create();

  try {
    var root = Yoga.Node.create(config);
    root.setWidth(100);
    root.setHeight(100);

    var root_child0 = Yoga.Node.create(config);
    root_child0.setMaxWidth(50);
    root_child0.setHeight(10);
    root.insertChild(root_child0, 0);
    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_LTR);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "100 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "50 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(50);;
    expect(
      root_child0.getComputedHeight(),
      "10 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(10);;

    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_RTL);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "100 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "50 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(50);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "50 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(50);;
    expect(
      root_child0.getComputedHeight(),
      "10 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(10);;
  } finally {
    if (typeof root !== "undefined") {
      root.freeRecursive();
    }

    config.free();
  }
});
it("max_height", function () {
  var config = Yoga.Config.create();

  try {
    var root = Yoga.Node.create(config);
    root.setFlexDirection(Yoga.FLEX_DIRECTION_ROW);
    root.setWidth(100);
    root.setHeight(100);

    var root_child0 = Yoga.Node.create(config);
    root_child0.setWidth(10);
    root_child0.setMaxHeight(50);
    root.insertChild(root_child0, 0);
    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_LTR);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "100 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "10 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(10);;
    expect(
      root_child0.getComputedHeight(),
      "50 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(50);;

    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_RTL);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "100 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "90 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(90);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "10 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(10);;
    expect(
      root_child0.getComputedHeight(),
      "50 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(50);;
  } finally {
    if (typeof root !== "undefined") {
      root.freeRecursive();
    }

    config.free();
  }
});
it("justify_content_min_max", function () {
  var config = Yoga.Config.create();

  try {
    var root = Yoga.Node.create(config);
    root.setJustifyContent(Yoga.JUSTIFY_CENTER);
    root.setWidth(100);
    root.setMinHeight(100);
    root.setMaxHeight(200);

    var root_child0 = Yoga.Node.create(config);
    root_child0.setWidth(60);
    root_child0.setHeight(60);
    root.insertChild(root_child0, 0);
    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_LTR);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "100 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "20 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(20);;
    expect(
      root_child0.getComputedWidth(),
      "60 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(60);;
    expect(
      root_child0.getComputedHeight(),
      "60 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(60);;

    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_RTL);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "100 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "40 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(40);;
    expect(
      root_child0.getComputedTop(),
      "20 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(20);;
    expect(
      root_child0.getComputedWidth(),
      "60 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(60);;
    expect(
      root_child0.getComputedHeight(),
      "60 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(60);;
  } finally {
    if (typeof root !== "undefined") {
      root.freeRecursive();
    }

    config.free();
  }
});
it("align_items_min_max", function () {
  var config = Yoga.Config.create();

  try {
    var root = Yoga.Node.create(config);
    root.setAlignItems(Yoga.ALIGN_CENTER);
    root.setMinWidth(100);
    root.setMaxWidth(200);
    root.setHeight(100);

    var root_child0 = Yoga.Node.create(config);
    root_child0.setWidth(60);
    root_child0.setHeight(60);
    root.insertChild(root_child0, 0);
    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_LTR);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "100 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "20 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(20);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "60 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(60);;
    expect(
      root_child0.getComputedHeight(),
      "60 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(60);;

    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_RTL);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "100 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "20 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(20);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "60 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(60);;
    expect(
      root_child0.getComputedHeight(),
      "60 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(60);;
  } finally {
    if (typeof root !== "undefined") {
      root.freeRecursive();
    }

    config.free();
  }
});
it("justify_content_overflow_min_max", function () {
  var config = Yoga.Config.create();

  try {
    var root = Yoga.Node.create(config);
    root.setJustifyContent(Yoga.JUSTIFY_CENTER);
    root.setMinHeight(100);
    root.setMaxHeight(110);

    var root_child0 = Yoga.Node.create(config);
    root_child0.setWidth(50);
    root_child0.setHeight(50);
    root.insertChild(root_child0, 0);

    var root_child1 = Yoga.Node.create(config);
    root_child1.setWidth(50);
    root_child1.setHeight(50);
    root.insertChild(root_child1, 1);

    var root_child2 = Yoga.Node.create(config);
    root_child2.setWidth(50);
    root_child2.setHeight(50);
    root.insertChild(root_child2, 2);
    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_LTR);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "50 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(50);;
    expect(
      root.getComputedHeight(),
      "110 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(110);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "-20 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(-20);;
    expect(
      root_child0.getComputedWidth(),
      "50 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(50);;
    expect(
      root_child0.getComputedHeight(),
      "50 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(50);;

    expect(
      root_child1.getComputedLeft(),
      "0 === root_child1.getComputedLeft() (" + root_child1.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child1.getComputedTop(),
      "30 === root_child1.getComputedTop() (" + root_child1.getComputedTop() + ")"
    ).toBe(30);;
    expect(
      root_child1.getComputedWidth(),
      "50 === root_child1.getComputedWidth() (" + root_child1.getComputedWidth() + ")"
    ).toBe(50);;
    expect(
      root_child1.getComputedHeight(),
      "50 === root_child1.getComputedHeight() (" + root_child1.getComputedHeight() + ")"
    ).toBe(50);;

    expect(
      root_child2.getComputedLeft(),
      "0 === root_child2.getComputedLeft() (" + root_child2.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child2.getComputedTop(),
      "80 === root_child2.getComputedTop() (" + root_child2.getComputedTop() + ")"
    ).toBe(80);;
    expect(
      root_child2.getComputedWidth(),
      "50 === root_child2.getComputedWidth() (" + root_child2.getComputedWidth() + ")"
    ).toBe(50);;
    expect(
      root_child2.getComputedHeight(),
      "50 === root_child2.getComputedHeight() (" + root_child2.getComputedHeight() + ")"
    ).toBe(50);;

    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_RTL);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "50 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(50);;
    expect(
      root.getComputedHeight(),
      "110 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(110);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "-20 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(-20);;
    expect(
      root_child0.getComputedWidth(),
      "50 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(50);;
    expect(
      root_child0.getComputedHeight(),
      "50 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(50);;

    expect(
      root_child1.getComputedLeft(),
      "0 === root_child1.getComputedLeft() (" + root_child1.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child1.getComputedTop(),
      "30 === root_child1.getComputedTop() (" + root_child1.getComputedTop() + ")"
    ).toBe(30);;
    expect(
      root_child1.getComputedWidth(),
      "50 === root_child1.getComputedWidth() (" + root_child1.getComputedWidth() + ")"
    ).toBe(50);;
    expect(
      root_child1.getComputedHeight(),
      "50 === root_child1.getComputedHeight() (" + root_child1.getComputedHeight() + ")"
    ).toBe(50);;

    expect(
      root_child2.getComputedLeft(),
      "0 === root_child2.getComputedLeft() (" + root_child2.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child2.getComputedTop(),
      "80 === root_child2.getComputedTop() (" + root_child2.getComputedTop() + ")"
    ).toBe(80);;
    expect(
      root_child2.getComputedWidth(),
      "50 === root_child2.getComputedWidth() (" + root_child2.getComputedWidth() + ")"
    ).toBe(50);;
    expect(
      root_child2.getComputedHeight(),
      "50 === root_child2.getComputedHeight() (" + root_child2.getComputedHeight() + ")"
    ).toBe(50);;
  } finally {
    if (typeof root !== "undefined") {
      root.freeRecursive();
    }

    config.free();
  }
});
it("flex_grow_to_min", function () {
  var config = Yoga.Config.create();

  try {
    var root = Yoga.Node.create(config);
    root.setWidth(100);
    root.setMinHeight(100);
    root.setMaxHeight(500);

    var root_child0 = Yoga.Node.create(config);
    root_child0.setFlexGrow(1);
    root_child0.setFlexShrink(1);
    root.insertChild(root_child0, 0);

    var root_child1 = Yoga.Node.create(config);
    root_child1.setHeight(50);
    root.insertChild(root_child1, 1);
    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_LTR);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "100 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "100 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child0.getComputedHeight(),
      "50 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(50);;

    expect(
      root_child1.getComputedLeft(),
      "0 === root_child1.getComputedLeft() (" + root_child1.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child1.getComputedTop(),
      "50 === root_child1.getComputedTop() (" + root_child1.getComputedTop() + ")"
    ).toBe(50);;
    expect(
      root_child1.getComputedWidth(),
      "100 === root_child1.getComputedWidth() (" + root_child1.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child1.getComputedHeight(),
      "50 === root_child1.getComputedHeight() (" + root_child1.getComputedHeight() + ")"
    ).toBe(50);;

    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_RTL);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "100 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "100 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child0.getComputedHeight(),
      "50 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(50);;

    expect(
      root_child1.getComputedLeft(),
      "0 === root_child1.getComputedLeft() (" + root_child1.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child1.getComputedTop(),
      "50 === root_child1.getComputedTop() (" + root_child1.getComputedTop() + ")"
    ).toBe(50);;
    expect(
      root_child1.getComputedWidth(),
      "100 === root_child1.getComputedWidth() (" + root_child1.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child1.getComputedHeight(),
      "50 === root_child1.getComputedHeight() (" + root_child1.getComputedHeight() + ")"
    ).toBe(50);;
  } finally {
    if (typeof root !== "undefined") {
      root.freeRecursive();
    }

    config.free();
  }
});
it("flex_grow_in_at_most_container", function () {
  var config = Yoga.Config.create();

  try {
    var root = Yoga.Node.create(config);
    root.setFlexDirection(Yoga.FLEX_DIRECTION_ROW);
    root.setAlignItems(Yoga.ALIGN_FLEX_START);
    root.setWidth(100);
    root.setHeight(100);

    var root_child0 = Yoga.Node.create(config);
    root_child0.setFlexDirection(Yoga.FLEX_DIRECTION_ROW);
    root.insertChild(root_child0, 0);

    var root_child0_child0 = Yoga.Node.create(config);
    root_child0_child0.setFlexGrow(1);
    root_child0_child0.setFlexBasis(0);
    root_child0.insertChild(root_child0_child0, 0);
    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_LTR);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "100 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "0 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedHeight(),
      "0 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(0);;

    expect(
      root_child0_child0.getComputedLeft(),
      "0 === root_child0_child0.getComputedLeft() (" + root_child0_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0.getComputedTop(),
      "0 === root_child0_child0.getComputedTop() (" + root_child0_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0.getComputedWidth(),
      "0 === root_child0_child0.getComputedWidth() (" + root_child0_child0.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0.getComputedHeight(),
      "0 === root_child0_child0.getComputedHeight() (" + root_child0_child0.getComputedHeight() + ")"
    ).toBe(0);;

    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_RTL);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "100 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "100 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(100);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "0 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedHeight(),
      "0 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(0);;

    expect(
      root_child0_child0.getComputedLeft(),
      "0 === root_child0_child0.getComputedLeft() (" + root_child0_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0.getComputedTop(),
      "0 === root_child0_child0.getComputedTop() (" + root_child0_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0.getComputedWidth(),
      "0 === root_child0_child0.getComputedWidth() (" + root_child0_child0.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0.getComputedHeight(),
      "0 === root_child0_child0.getComputedHeight() (" + root_child0_child0.getComputedHeight() + ")"
    ).toBe(0);;
  } finally {
    if (typeof root !== "undefined") {
      root.freeRecursive();
    }

    config.free();
  }
});
it("flex_grow_child", function () {
  var config = Yoga.Config.create();

  try {
    var root = Yoga.Node.create(config);
    root.setFlexDirection(Yoga.FLEX_DIRECTION_ROW);

    var root_child0 = Yoga.Node.create(config);
    root_child0.setFlexGrow(1);
    root_child0.setFlexBasis(0);
    root_child0.setHeight(100);
    root.insertChild(root_child0, 0);
    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_LTR);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "0 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "0 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedHeight(),
      "100 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(100);;

    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_RTL);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "0 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "0 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedHeight(),
      "100 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(100);;
  } finally {
    if (typeof root !== "undefined") {
      root.freeRecursive();
    }

    config.free();
  }
});
it("flex_grow_within_constrained_min_max_column", function () {
  var config = Yoga.Config.create();

  try {
    var root = Yoga.Node.create(config);
    root.setMinHeight(100);
    root.setMaxHeight(200);

    var root_child0 = Yoga.Node.create(config);
    root_child0.setFlexGrow(1);
    root.insertChild(root_child0, 0);

    var root_child1 = Yoga.Node.create(config);
    root_child1.setHeight(50);
    root.insertChild(root_child1, 1);
    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_LTR);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "0 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "0 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedHeight(),
      "50 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(50);;

    expect(
      root_child1.getComputedLeft(),
      "0 === root_child1.getComputedLeft() (" + root_child1.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child1.getComputedTop(),
      "50 === root_child1.getComputedTop() (" + root_child1.getComputedTop() + ")"
    ).toBe(50);;
    expect(
      root_child1.getComputedWidth(),
      "0 === root_child1.getComputedWidth() (" + root_child1.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root_child1.getComputedHeight(),
      "50 === root_child1.getComputedHeight() (" + root_child1.getComputedHeight() + ")"
    ).toBe(50);;

    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_RTL);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "0 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "0 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedHeight(),
      "50 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(50);;

    expect(
      root_child1.getComputedLeft(),
      "0 === root_child1.getComputedLeft() (" + root_child1.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child1.getComputedTop(),
      "50 === root_child1.getComputedTop() (" + root_child1.getComputedTop() + ")"
    ).toBe(50);;
    expect(
      root_child1.getComputedWidth(),
      "0 === root_child1.getComputedWidth() (" + root_child1.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root_child1.getComputedHeight(),
      "50 === root_child1.getComputedHeight() (" + root_child1.getComputedHeight() + ")"
    ).toBe(50);;
  } finally {
    if (typeof root !== "undefined") {
      root.freeRecursive();
    }

    config.free();
  }
});
it("flex_grow_within_max_width", function () {
  var config = Yoga.Config.create();

  try {
    var root = Yoga.Node.create(config);
    root.setWidth(200);
    root.setHeight(100);

    var root_child0 = Yoga.Node.create(config);
    root_child0.setFlexDirection(Yoga.FLEX_DIRECTION_ROW);
    root_child0.setMaxWidth(100);
    root.insertChild(root_child0, 0);

    var root_child0_child0 = Yoga.Node.create(config);
    root_child0_child0.setFlexGrow(1);
    root_child0_child0.setHeight(20);
    root_child0.insertChild(root_child0_child0, 0);
    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_LTR);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "200 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(200);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "100 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child0.getComputedHeight(),
      "20 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(20);;

    expect(
      root_child0_child0.getComputedLeft(),
      "0 === root_child0_child0.getComputedLeft() (" + root_child0_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0.getComputedTop(),
      "0 === root_child0_child0.getComputedTop() (" + root_child0_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0.getComputedWidth(),
      "100 === root_child0_child0.getComputedWidth() (" + root_child0_child0.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child0_child0.getComputedHeight(),
      "20 === root_child0_child0.getComputedHeight() (" + root_child0_child0.getComputedHeight() + ")"
    ).toBe(20);;

    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_RTL);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "200 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(200);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "100 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(100);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "100 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child0.getComputedHeight(),
      "20 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(20);;

    expect(
      root_child0_child0.getComputedLeft(),
      "0 === root_child0_child0.getComputedLeft() (" + root_child0_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0.getComputedTop(),
      "0 === root_child0_child0.getComputedTop() (" + root_child0_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0.getComputedWidth(),
      "100 === root_child0_child0.getComputedWidth() (" + root_child0_child0.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child0_child0.getComputedHeight(),
      "20 === root_child0_child0.getComputedHeight() (" + root_child0_child0.getComputedHeight() + ")"
    ).toBe(20);;
  } finally {
    if (typeof root !== "undefined") {
      root.freeRecursive();
    }

    config.free();
  }
});
it("flex_grow_within_constrained_max_width", function () {
  var config = Yoga.Config.create();

  try {
    var root = Yoga.Node.create(config);
    root.setWidth(200);
    root.setHeight(100);

    var root_child0 = Yoga.Node.create(config);
    root_child0.setFlexDirection(Yoga.FLEX_DIRECTION_ROW);
    root_child0.setMaxWidth(300);
    root.insertChild(root_child0, 0);

    var root_child0_child0 = Yoga.Node.create(config);
    root_child0_child0.setFlexGrow(1);
    root_child0_child0.setHeight(20);
    root_child0.insertChild(root_child0_child0, 0);
    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_LTR);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "200 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(200);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "200 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(200);;
    expect(
      root_child0.getComputedHeight(),
      "20 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(20);;

    expect(
      root_child0_child0.getComputedLeft(),
      "0 === root_child0_child0.getComputedLeft() (" + root_child0_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0.getComputedTop(),
      "0 === root_child0_child0.getComputedTop() (" + root_child0_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0.getComputedWidth(),
      "200 === root_child0_child0.getComputedWidth() (" + root_child0_child0.getComputedWidth() + ")"
    ).toBe(200);;
    expect(
      root_child0_child0.getComputedHeight(),
      "20 === root_child0_child0.getComputedHeight() (" + root_child0_child0.getComputedHeight() + ")"
    ).toBe(20);;

    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_RTL);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "200 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(200);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "200 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(200);;
    expect(
      root_child0.getComputedHeight(),
      "20 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(20);;

    expect(
      root_child0_child0.getComputedLeft(),
      "0 === root_child0_child0.getComputedLeft() (" + root_child0_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0.getComputedTop(),
      "0 === root_child0_child0.getComputedTop() (" + root_child0_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0.getComputedWidth(),
      "200 === root_child0_child0.getComputedWidth() (" + root_child0_child0.getComputedWidth() + ")"
    ).toBe(200);;
    expect(
      root_child0_child0.getComputedHeight(),
      "20 === root_child0_child0.getComputedHeight() (" + root_child0_child0.getComputedHeight() + ")"
    ).toBe(20);;
  } finally {
    if (typeof root !== "undefined") {
      root.freeRecursive();
    }

    config.free();
  }
});
it("flex_root_ignored", function () {
  var config = Yoga.Config.create();

  try {
    var root = Yoga.Node.create(config);
    root.setFlexGrow(1);
    root.setWidth(100);
    root.setMinHeight(100);
    root.setMaxHeight(500);

    var root_child0 = Yoga.Node.create(config);
    root_child0.setFlexGrow(1);
    root_child0.setFlexBasis(200);
    root.insertChild(root_child0, 0);

    var root_child1 = Yoga.Node.create(config);
    root_child1.setHeight(100);
    root.insertChild(root_child1, 1);
    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_LTR);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "100 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root.getComputedHeight(),
      "300 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(300);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "100 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child0.getComputedHeight(),
      "200 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(200);;

    expect(
      root_child1.getComputedLeft(),
      "0 === root_child1.getComputedLeft() (" + root_child1.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child1.getComputedTop(),
      "200 === root_child1.getComputedTop() (" + root_child1.getComputedTop() + ")"
    ).toBe(200);;
    expect(
      root_child1.getComputedWidth(),
      "100 === root_child1.getComputedWidth() (" + root_child1.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child1.getComputedHeight(),
      "100 === root_child1.getComputedHeight() (" + root_child1.getComputedHeight() + ")"
    ).toBe(100);;

    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_RTL);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "100 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root.getComputedHeight(),
      "300 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(300);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "100 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child0.getComputedHeight(),
      "200 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(200);;

    expect(
      root_child1.getComputedLeft(),
      "0 === root_child1.getComputedLeft() (" + root_child1.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child1.getComputedTop(),
      "200 === root_child1.getComputedTop() (" + root_child1.getComputedTop() + ")"
    ).toBe(200);;
    expect(
      root_child1.getComputedWidth(),
      "100 === root_child1.getComputedWidth() (" + root_child1.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child1.getComputedHeight(),
      "100 === root_child1.getComputedHeight() (" + root_child1.getComputedHeight() + ")"
    ).toBe(100);;
  } finally {
    if (typeof root !== "undefined") {
      root.freeRecursive();
    }

    config.free();
  }
});
it("flex_grow_root_minimized", function () {
  var config = Yoga.Config.create();

  try {
    var root = Yoga.Node.create(config);
    root.setWidth(100);
    root.setMinHeight(100);
    root.setMaxHeight(500);

    var root_child0 = Yoga.Node.create(config);
    root_child0.setFlexGrow(1);
    root_child0.setMinHeight(100);
    root_child0.setMaxHeight(500);
    root.insertChild(root_child0, 0);

    var root_child0_child0 = Yoga.Node.create(config);
    root_child0_child0.setFlexGrow(1);
    root_child0_child0.setFlexBasis(200);
    root_child0.insertChild(root_child0_child0, 0);

    var root_child0_child1 = Yoga.Node.create(config);
    root_child0_child1.setHeight(100);
    root_child0.insertChild(root_child0_child1, 1);
    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_LTR);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "100 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root.getComputedHeight(),
      "300 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(300);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "100 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child0.getComputedHeight(),
      "300 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(300);;

    expect(
      root_child0_child0.getComputedLeft(),
      "0 === root_child0_child0.getComputedLeft() (" + root_child0_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0.getComputedTop(),
      "0 === root_child0_child0.getComputedTop() (" + root_child0_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0.getComputedWidth(),
      "100 === root_child0_child0.getComputedWidth() (" + root_child0_child0.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child0_child0.getComputedHeight(),
      "200 === root_child0_child0.getComputedHeight() (" + root_child0_child0.getComputedHeight() + ")"
    ).toBe(200);;

    expect(
      root_child0_child1.getComputedLeft(),
      "0 === root_child0_child1.getComputedLeft() (" + root_child0_child1.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child1.getComputedTop(),
      "200 === root_child0_child1.getComputedTop() (" + root_child0_child1.getComputedTop() + ")"
    ).toBe(200);;
    expect(
      root_child0_child1.getComputedWidth(),
      "100 === root_child0_child1.getComputedWidth() (" + root_child0_child1.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child0_child1.getComputedHeight(),
      "100 === root_child0_child1.getComputedHeight() (" + root_child0_child1.getComputedHeight() + ")"
    ).toBe(100);;

    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_RTL);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "100 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root.getComputedHeight(),
      "300 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(300);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "100 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child0.getComputedHeight(),
      "300 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(300);;

    expect(
      root_child0_child0.getComputedLeft(),
      "0 === root_child0_child0.getComputedLeft() (" + root_child0_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0.getComputedTop(),
      "0 === root_child0_child0.getComputedTop() (" + root_child0_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0.getComputedWidth(),
      "100 === root_child0_child0.getComputedWidth() (" + root_child0_child0.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child0_child0.getComputedHeight(),
      "200 === root_child0_child0.getComputedHeight() (" + root_child0_child0.getComputedHeight() + ")"
    ).toBe(200);;

    expect(
      root_child0_child1.getComputedLeft(),
      "0 === root_child0_child1.getComputedLeft() (" + root_child0_child1.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child1.getComputedTop(),
      "200 === root_child0_child1.getComputedTop() (" + root_child0_child1.getComputedTop() + ")"
    ).toBe(200);;
    expect(
      root_child0_child1.getComputedWidth(),
      "100 === root_child0_child1.getComputedWidth() (" + root_child0_child1.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child0_child1.getComputedHeight(),
      "100 === root_child0_child1.getComputedHeight() (" + root_child0_child1.getComputedHeight() + ")"
    ).toBe(100);;
  } finally {
    if (typeof root !== "undefined") {
      root.freeRecursive();
    }

    config.free();
  }
});
it("flex_grow_height_maximized", function () {
  var config = Yoga.Config.create();

  try {
    var root = Yoga.Node.create(config);
    root.setWidth(100);
    root.setHeight(500);

    var root_child0 = Yoga.Node.create(config);
    root_child0.setFlexGrow(1);
    root_child0.setMinHeight(100);
    root_child0.setMaxHeight(500);
    root.insertChild(root_child0, 0);

    var root_child0_child0 = Yoga.Node.create(config);
    root_child0_child0.setFlexGrow(1);
    root_child0_child0.setFlexBasis(200);
    root_child0.insertChild(root_child0_child0, 0);

    var root_child0_child1 = Yoga.Node.create(config);
    root_child0_child1.setHeight(100);
    root_child0.insertChild(root_child0_child1, 1);
    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_LTR);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "100 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root.getComputedHeight(),
      "500 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(500);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "100 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child0.getComputedHeight(),
      "500 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(500);;

    expect(
      root_child0_child0.getComputedLeft(),
      "0 === root_child0_child0.getComputedLeft() (" + root_child0_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0.getComputedTop(),
      "0 === root_child0_child0.getComputedTop() (" + root_child0_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0.getComputedWidth(),
      "100 === root_child0_child0.getComputedWidth() (" + root_child0_child0.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child0_child0.getComputedHeight(),
      "400 === root_child0_child0.getComputedHeight() (" + root_child0_child0.getComputedHeight() + ")"
    ).toBe(400);;

    expect(
      root_child0_child1.getComputedLeft(),
      "0 === root_child0_child1.getComputedLeft() (" + root_child0_child1.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child1.getComputedTop(),
      "400 === root_child0_child1.getComputedTop() (" + root_child0_child1.getComputedTop() + ")"
    ).toBe(400);;
    expect(
      root_child0_child1.getComputedWidth(),
      "100 === root_child0_child1.getComputedWidth() (" + root_child0_child1.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child0_child1.getComputedHeight(),
      "100 === root_child0_child1.getComputedHeight() (" + root_child0_child1.getComputedHeight() + ")"
    ).toBe(100);;

    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_RTL);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "100 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root.getComputedHeight(),
      "500 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(500);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "100 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child0.getComputedHeight(),
      "500 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(500);;

    expect(
      root_child0_child0.getComputedLeft(),
      "0 === root_child0_child0.getComputedLeft() (" + root_child0_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0.getComputedTop(),
      "0 === root_child0_child0.getComputedTop() (" + root_child0_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0.getComputedWidth(),
      "100 === root_child0_child0.getComputedWidth() (" + root_child0_child0.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child0_child0.getComputedHeight(),
      "400 === root_child0_child0.getComputedHeight() (" + root_child0_child0.getComputedHeight() + ")"
    ).toBe(400);;

    expect(
      root_child0_child1.getComputedLeft(),
      "0 === root_child0_child1.getComputedLeft() (" + root_child0_child1.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child1.getComputedTop(),
      "400 === root_child0_child1.getComputedTop() (" + root_child0_child1.getComputedTop() + ")"
    ).toBe(400);;
    expect(
      root_child0_child1.getComputedWidth(),
      "100 === root_child0_child1.getComputedWidth() (" + root_child0_child1.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child0_child1.getComputedHeight(),
      "100 === root_child0_child1.getComputedHeight() (" + root_child0_child1.getComputedHeight() + ")"
    ).toBe(100);;
  } finally {
    if (typeof root !== "undefined") {
      root.freeRecursive();
    }

    config.free();
  }
});
it("flex_grow_within_constrained_min_row", function () {
  var config = Yoga.Config.create();

  try {
    var root = Yoga.Node.create(config);
    root.setFlexDirection(Yoga.FLEX_DIRECTION_ROW);
    root.setMinWidth(100);
    root.setHeight(100);

    var root_child0 = Yoga.Node.create(config);
    root_child0.setFlexGrow(1);
    root.insertChild(root_child0, 0);

    var root_child1 = Yoga.Node.create(config);
    root_child1.setWidth(50);
    root.insertChild(root_child1, 1);
    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_LTR);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "100 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "50 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(50);;
    expect(
      root_child0.getComputedHeight(),
      "100 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child1.getComputedLeft(),
      "50 === root_child1.getComputedLeft() (" + root_child1.getComputedLeft() + ")"
    ).toBe(50);;
    expect(
      root_child1.getComputedTop(),
      "0 === root_child1.getComputedTop() (" + root_child1.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child1.getComputedWidth(),
      "50 === root_child1.getComputedWidth() (" + root_child1.getComputedWidth() + ")"
    ).toBe(50);;
    expect(
      root_child1.getComputedHeight(),
      "100 === root_child1.getComputedHeight() (" + root_child1.getComputedHeight() + ")"
    ).toBe(100);;

    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_RTL);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "100 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "50 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(50);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "50 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(50);;
    expect(
      root_child0.getComputedHeight(),
      "100 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child1.getComputedLeft(),
      "0 === root_child1.getComputedLeft() (" + root_child1.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child1.getComputedTop(),
      "0 === root_child1.getComputedTop() (" + root_child1.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child1.getComputedWidth(),
      "50 === root_child1.getComputedWidth() (" + root_child1.getComputedWidth() + ")"
    ).toBe(50);;
    expect(
      root_child1.getComputedHeight(),
      "100 === root_child1.getComputedHeight() (" + root_child1.getComputedHeight() + ")"
    ).toBe(100);;
  } finally {
    if (typeof root !== "undefined") {
      root.freeRecursive();
    }

    config.free();
  }
});
it("flex_grow_within_constrained_min_column", function () {
  var config = Yoga.Config.create();

  try {
    var root = Yoga.Node.create(config);
    root.setMinHeight(100);

    var root_child0 = Yoga.Node.create(config);
    root_child0.setFlexGrow(1);
    root.insertChild(root_child0, 0);

    var root_child1 = Yoga.Node.create(config);
    root_child1.setHeight(50);
    root.insertChild(root_child1, 1);
    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_LTR);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "0 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "0 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedHeight(),
      "50 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(50);;

    expect(
      root_child1.getComputedLeft(),
      "0 === root_child1.getComputedLeft() (" + root_child1.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child1.getComputedTop(),
      "50 === root_child1.getComputedTop() (" + root_child1.getComputedTop() + ")"
    ).toBe(50);;
    expect(
      root_child1.getComputedWidth(),
      "0 === root_child1.getComputedWidth() (" + root_child1.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root_child1.getComputedHeight(),
      "50 === root_child1.getComputedHeight() (" + root_child1.getComputedHeight() + ")"
    ).toBe(50);;

    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_RTL);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "0 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "0 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedHeight(),
      "50 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(50);;

    expect(
      root_child1.getComputedLeft(),
      "0 === root_child1.getComputedLeft() (" + root_child1.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child1.getComputedTop(),
      "50 === root_child1.getComputedTop() (" + root_child1.getComputedTop() + ")"
    ).toBe(50);;
    expect(
      root_child1.getComputedWidth(),
      "0 === root_child1.getComputedWidth() (" + root_child1.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root_child1.getComputedHeight(),
      "50 === root_child1.getComputedHeight() (" + root_child1.getComputedHeight() + ")"
    ).toBe(50);;
  } finally {
    if (typeof root !== "undefined") {
      root.freeRecursive();
    }

    config.free();
  }
});
it("flex_grow_within_constrained_max_row", function () {
  var config = Yoga.Config.create();

  try {
    var root = Yoga.Node.create(config);
    root.setWidth(200);

    var root_child0 = Yoga.Node.create(config);
    root_child0.setFlexDirection(Yoga.FLEX_DIRECTION_ROW);
    root_child0.setMaxWidth(100);
    root_child0.setHeight(100);
    root.insertChild(root_child0, 0);

    var root_child0_child0 = Yoga.Node.create(config);
    root_child0_child0.setFlexShrink(1);
    root_child0_child0.setFlexBasis(100);
    root_child0.insertChild(root_child0_child0, 0);

    var root_child0_child1 = Yoga.Node.create(config);
    root_child0_child1.setWidth(50);
    root_child0.insertChild(root_child0_child1, 1);
    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_LTR);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "200 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(200);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "100 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child0.getComputedHeight(),
      "100 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0_child0.getComputedLeft(),
      "0 === root_child0_child0.getComputedLeft() (" + root_child0_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0.getComputedTop(),
      "0 === root_child0_child0.getComputedTop() (" + root_child0_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0.getComputedWidth(),
      "50 === root_child0_child0.getComputedWidth() (" + root_child0_child0.getComputedWidth() + ")"
    ).toBe(50);;
    expect(
      root_child0_child0.getComputedHeight(),
      "100 === root_child0_child0.getComputedHeight() (" + root_child0_child0.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0_child1.getComputedLeft(),
      "50 === root_child0_child1.getComputedLeft() (" + root_child0_child1.getComputedLeft() + ")"
    ).toBe(50);;
    expect(
      root_child0_child1.getComputedTop(),
      "0 === root_child0_child1.getComputedTop() (" + root_child0_child1.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child1.getComputedWidth(),
      "50 === root_child0_child1.getComputedWidth() (" + root_child0_child1.getComputedWidth() + ")"
    ).toBe(50);;
    expect(
      root_child0_child1.getComputedHeight(),
      "100 === root_child0_child1.getComputedHeight() (" + root_child0_child1.getComputedHeight() + ")"
    ).toBe(100);;

    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_RTL);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "200 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(200);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "100 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(100);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "100 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child0.getComputedHeight(),
      "100 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0_child0.getComputedLeft(),
      "50 === root_child0_child0.getComputedLeft() (" + root_child0_child0.getComputedLeft() + ")"
    ).toBe(50);;
    expect(
      root_child0_child0.getComputedTop(),
      "0 === root_child0_child0.getComputedTop() (" + root_child0_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child0.getComputedWidth(),
      "50 === root_child0_child0.getComputedWidth() (" + root_child0_child0.getComputedWidth() + ")"
    ).toBe(50);;
    expect(
      root_child0_child0.getComputedHeight(),
      "100 === root_child0_child0.getComputedHeight() (" + root_child0_child0.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0_child1.getComputedLeft(),
      "0 === root_child0_child1.getComputedLeft() (" + root_child0_child1.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0_child1.getComputedTop(),
      "0 === root_child0_child1.getComputedTop() (" + root_child0_child1.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0_child1.getComputedWidth(),
      "50 === root_child0_child1.getComputedWidth() (" + root_child0_child1.getComputedWidth() + ")"
    ).toBe(50);;
    expect(
      root_child0_child1.getComputedHeight(),
      "100 === root_child0_child1.getComputedHeight() (" + root_child0_child1.getComputedHeight() + ")"
    ).toBe(100);;
  } finally {
    if (typeof root !== "undefined") {
      root.freeRecursive();
    }

    config.free();
  }
});
it("flex_grow_within_constrained_max_column", function () {
  var config = Yoga.Config.create();

  try {
    var root = Yoga.Node.create(config);
    root.setWidth(100);
    root.setMaxHeight(100);

    var root_child0 = Yoga.Node.create(config);
    root_child0.setFlexShrink(1);
    root_child0.setFlexBasis(100);
    root.insertChild(root_child0, 0);

    var root_child1 = Yoga.Node.create(config);
    root_child1.setHeight(50);
    root.insertChild(root_child1, 1);
    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_LTR);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "100 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "100 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child0.getComputedHeight(),
      "50 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(50);;

    expect(
      root_child1.getComputedLeft(),
      "0 === root_child1.getComputedLeft() (" + root_child1.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child1.getComputedTop(),
      "50 === root_child1.getComputedTop() (" + root_child1.getComputedTop() + ")"
    ).toBe(50);;
    expect(
      root_child1.getComputedWidth(),
      "100 === root_child1.getComputedWidth() (" + root_child1.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child1.getComputedHeight(),
      "50 === root_child1.getComputedHeight() (" + root_child1.getComputedHeight() + ")"
    ).toBe(50);;

    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_RTL);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "100 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "100 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child0.getComputedHeight(),
      "50 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(50);;

    expect(
      root_child1.getComputedLeft(),
      "0 === root_child1.getComputedLeft() (" + root_child1.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child1.getComputedTop(),
      "50 === root_child1.getComputedTop() (" + root_child1.getComputedTop() + ")"
    ).toBe(50);;
    expect(
      root_child1.getComputedWidth(),
      "100 === root_child1.getComputedWidth() (" + root_child1.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child1.getComputedHeight(),
      "50 === root_child1.getComputedHeight() (" + root_child1.getComputedHeight() + ")"
    ).toBe(50);;
  } finally {
    if (typeof root !== "undefined") {
      root.freeRecursive();
    }

    config.free();
  }
});
it("child_min_max_width_flexing", function () {
  var config = Yoga.Config.create();

  try {
    var root = Yoga.Node.create(config);
    root.setFlexDirection(Yoga.FLEX_DIRECTION_ROW);
    root.setWidth(120);
    root.setHeight(50);

    var root_child0 = Yoga.Node.create(config);
    root_child0.setFlexGrow(1);
    root_child0.setFlexBasis(0);
    root_child0.setMinWidth(60);
    root.insertChild(root_child0, 0);

    var root_child1 = Yoga.Node.create(config);
    root_child1.setFlexGrow(1);
    root_child1.setFlexBasis("50%");
    root_child1.setMaxWidth(20);
    root.insertChild(root_child1, 1);
    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_LTR);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "120 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(120);;
    expect(
      root.getComputedHeight(),
      "50 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(50);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "100 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child0.getComputedHeight(),
      "50 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(50);;

    expect(
      root_child1.getComputedLeft(),
      "100 === root_child1.getComputedLeft() (" + root_child1.getComputedLeft() + ")"
    ).toBe(100);;
    expect(
      root_child1.getComputedTop(),
      "0 === root_child1.getComputedTop() (" + root_child1.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child1.getComputedWidth(),
      "20 === root_child1.getComputedWidth() (" + root_child1.getComputedWidth() + ")"
    ).toBe(20);;
    expect(
      root_child1.getComputedHeight(),
      "50 === root_child1.getComputedHeight() (" + root_child1.getComputedHeight() + ")"
    ).toBe(50);;

    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_RTL);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "120 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(120);;
    expect(
      root.getComputedHeight(),
      "50 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(50);;

    expect(
      root_child0.getComputedLeft(),
      "20 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(20);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "100 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root_child0.getComputedHeight(),
      "50 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(50);;

    expect(
      root_child1.getComputedLeft(),
      "0 === root_child1.getComputedLeft() (" + root_child1.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child1.getComputedTop(),
      "0 === root_child1.getComputedTop() (" + root_child1.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child1.getComputedWidth(),
      "20 === root_child1.getComputedWidth() (" + root_child1.getComputedWidth() + ")"
    ).toBe(20);;
    expect(
      root_child1.getComputedHeight(),
      "50 === root_child1.getComputedHeight() (" + root_child1.getComputedHeight() + ")"
    ).toBe(50);;
  } finally {
    if (typeof root !== "undefined") {
      root.freeRecursive();
    }

    config.free();
  }
});
it("min_width_overrides_width", function () {
  var config = Yoga.Config.create();

  try {
    var root = Yoga.Node.create(config);
    root.setWidth(50);
    root.setMinWidth(100);
    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_LTR);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "100 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root.getComputedHeight(),
      "0 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(0);;

    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_RTL);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "100 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root.getComputedHeight(),
      "0 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(0);;
  } finally {
    if (typeof root !== "undefined") {
      root.freeRecursive();
    }

    config.free();
  }
});
it("max_width_overrides_width", function () {
  var config = Yoga.Config.create();

  try {
    var root = Yoga.Node.create(config);
    root.setWidth(200);
    root.setMaxWidth(100);
    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_LTR);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "100 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root.getComputedHeight(),
      "0 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(0);;

    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_RTL);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "100 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root.getComputedHeight(),
      "0 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(0);;
  } finally {
    if (typeof root !== "undefined") {
      root.freeRecursive();
    }

    config.free();
  }
});
it("min_height_overrides_height", function () {
  var config = Yoga.Config.create();

  try {
    var root = Yoga.Node.create(config);
    root.setHeight(50);
    root.setMinHeight(100);
    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_LTR);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "0 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_RTL);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "0 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;
  } finally {
    if (typeof root !== "undefined") {
      root.freeRecursive();
    }

    config.free();
  }
});
it("max_height_overrides_height", function () {
  var config = Yoga.Config.create();

  try {
    var root = Yoga.Node.create(config);
    root.setHeight(200);
    root.setMaxHeight(100);
    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_LTR);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "0 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_RTL);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "0 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(0);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;
  } finally {
    if (typeof root !== "undefined") {
      root.freeRecursive();
    }

    config.free();
  }
});
it("min_max_percent_no_width_height", function () {
  var config = Yoga.Config.create();

  try {
    var root = Yoga.Node.create(config);
    root.setAlignItems(Yoga.ALIGN_FLEX_START);
    root.setWidth(100);
    root.setHeight(100);

    var root_child0 = Yoga.Node.create(config);
    root_child0.setMinWidth("10%");
    root_child0.setMaxWidth("10%");
    root_child0.setMinHeight("10%");
    root_child0.setMaxHeight("10%");
    root.insertChild(root_child0, 0);
    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_LTR);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "100 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "0 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "10 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(10);;
    expect(
      root_child0.getComputedHeight(),
      "10 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(10);;

    root.calculateLayout(Yoga.UNDEFINED, Yoga.UNDEFINED, Yoga.DIRECTION_RTL);

    expect(
      root.getComputedLeft(),
      "0 === root.getComputedLeft() (" + root.getComputedLeft() + ")"
    ).toBe(0);;
    expect(
      root.getComputedTop(),
      "0 === root.getComputedTop() (" + root.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root.getComputedWidth(),
      "100 === root.getComputedWidth() (" + root.getComputedWidth() + ")"
    ).toBe(100);;
    expect(
      root.getComputedHeight(),
      "100 === root.getComputedHeight() (" + root.getComputedHeight() + ")"
    ).toBe(100);;

    expect(
      root_child0.getComputedLeft(),
      "90 === root_child0.getComputedLeft() (" + root_child0.getComputedLeft() + ")"
    ).toBe(90);;
    expect(
      root_child0.getComputedTop(),
      "0 === root_child0.getComputedTop() (" + root_child0.getComputedTop() + ")"
    ).toBe(0);;
    expect(
      root_child0.getComputedWidth(),
      "10 === root_child0.getComputedWidth() (" + root_child0.getComputedWidth() + ")"
    ).toBe(10);;
    expect(
      root_child0.getComputedHeight(),
      "10 === root_child0.getComputedHeight() (" + root_child0.getComputedHeight() + ")"
    ).toBe(10);;
  } finally {
    if (typeof root !== "undefined") {
      root.freeRecursive();
    }

    config.free();
  }
});
